/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import pbo_2310010218.CRUD;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.*;
import javax.swing.*;

/**
 *
 * @author LENOVO
 */
public class framesk extends javax.swing.JFrame {

    private CRUD crudObj;

    /**
     * Creates new form framesk
     */
    public framesk() {
        initComponents();
        this.setLocationRelativeTo(null);
        crudObj = new CRUD();
        
        crudObj.loadData(jTable1, "SELECT * FROM sk");

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });

        TxtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCariKeyReleased(evt);
            }
        });
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        int baris = jTable1.getSelectedRow();
        if (baris == -1) {
            return;
        }
        TxtID.setText(jTable1.getValueAt(baris, 0).toString());
        TxtNosk.setText(jTable1.getValueAt(baris, 1).toString());
        TxtTanggalsk.setText(jTable1.getValueAt(baris, 2).toString());
        TxtNama.setText(jTable1.getValueAt(baris, 3) != null ? jTable1.getValueAt(baris, 3).toString() : "");
        TxtKeterangan.setText(jTable1.getValueAt(baris, 4) != null ? jTable1.getValueAt(baris, 4).toString() : "");
        TxtFile.setText(jTable1.getValueAt(baris, 5) != null ? jTable1.getValueAt(baris, 5).toString() : "");
    }

    private void TxtCariKeyReleased(java.awt.event.KeyEvent evt) {
        try {
            String c = TxtCari.getText();
            String cari = "SELECT * FROM sk WHERE ids LIKE '%" + c + "%' OR nosk LIKE '%" + c + "%' OR nama LIKE '%" + c + "%'";
            crudObj.loadData(jTable1, cari);
        } catch (Exception e) {
            System.out.print(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtNosk = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtTanggalsk = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtKeterangan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtFile = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtID = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        TxtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("No sk");

        TxtTanggalsk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTanggalskActionPerformed(evt);
            }
        });

        jLabel3.setText("Tanggal sk (YYYY-MM-DD)");

        jLabel4.setText("Nama");

        jLabel5.setText("Keterangan");

        jLabel6.setText("file");

        jLabel1.setText("ID");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("FORM SURAT KEPUTUSAN (SK)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(TxtCari)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUbah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtID)
                                .addComponent(TxtNosk)
                                .addComponent(TxtTanggalsk)
                                .addComponent(TxtNama)
                                .addComponent(TxtKeterangan)
                                .addComponent(TxtFile, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNosk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtTanggalsk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtTanggalskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTanggalskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTanggalskActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String ids = TxtID.getText();
            String nosk = TxtNosk.getText();
            String tglsk = TxtTanggalsk.getText();
            String nama = TxtNama.getText();
            String ket = TxtKeterangan.getText();
            String file = TxtFile.getText();

            if (ids.isEmpty() || nosk.isEmpty() || tglsk.isEmpty()) {
                JOptionPane.showMessageDialog(null, "ID, No SK, dan Tanggal SK wajib diisi!");
                return;
            }

            crudObj.simpanSKStatement(ids, nosk, tglsk, nama, ket, file);

            if (crudObj.validasi) {
                TxtNosk.setText(crudObj.var_nosk_sk);
                TxtTanggalsk.setText(crudObj.var_tglsk_sk);
                TxtNama.setText(crudObj.var_nama_sk);
                TxtKeterangan.setText(crudObj.var_ket_sk);
                TxtFile.setText(crudObj.var_file_sk);
            }
            crudObj.loadData(jTable1, "SELECT * FROM sk");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {
        if (
            TxtID.getText().isEmpty() ||
            TxtNosk.getText().isEmpty() ||
            TxtTanggalsk.getText().isEmpty()
           ){
            JOptionPane.showMessageDialog(null, "Pilih data dari tabel terlebih dahulu!");
            return;
        }

        crudObj.ubahSKPrepared(
                TxtID.getText(),
                TxtNosk.getText(),
                TxtTanggalsk.getText(),
                TxtNama.getText(),
                TxtKeterangan.getText(),
                TxtFile.getText()
        );
        crudObj.loadData(jTable1, "SELECT * FROM sk");
    }

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {
        if (TxtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih data dari tabel untuk dihapus!");
            return;
        }
        int konfirmasi = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data ID: " + TxtID.getText() + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            
            crudObj.hapusSKPrepared(TxtID.getText());
            
            TxtID.setText(null);
            TxtNosk.setText(null);
            TxtTanggalsk.setText(null);
            TxtNama.setText(null);
            TxtKeterangan.setText(null);
            TxtFile.setText(null);
            
            crudObj.loadData(jTable1, "SELECT * FROM sk");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framesk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtCari;
    private javax.swing.JTextField TxtFile;
    private javax.swing.JTextField TxtID;
    private javax.swing.JTextField TxtKeterangan;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtNosk;
    private javax.swing.JTextField TxtTanggalsk;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}