/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import pbo_2310010218.CRUD;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.*;
import javax.swing.*;

/**
 *
 * @author LENOVO
 */
public class framesuratkeluar extends javax.swing.JFrame {

    private CRUD crudObj;

    /**
     * Creates new form framesuratkeluar
     */
    public framesuratkeluar() {
        initComponents();
        this.setLocationRelativeTo(null);
        crudObj = new CRUD();
        
        crudObj.loadData(jTable1, "SELECT * FROM surat_keluar");

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });

        TxtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCariKeyReleased(evt);
            }
        });
    }
    
    private void clearForm() {
        TxtID.setText(null);
        TxtNoSurat.setText(null);
        TxtTanggal.setText(null);
        TxtPerihal.setText(null);
        TxtTujuan.setText(null);
        TxtPengirim.setText(null);
        TxtFile.setText(null);
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        int baris = jTable1.getSelectedRow();
        if (baris == -1) {
            return;
        }
        TxtID.setText(jTable1.getValueAt(baris, 0).toString());
        TxtNoSurat.setText(jTable1.getValueAt(baris, 1).toString());
        TxtTanggal.setText(jTable1.getValueAt(baris, 2).toString());
        TxtPerihal.setText(jTable1.getValueAt(baris, 3) != null ? jTable1.getValueAt(baris, 3).toString() : "");
        TxtTujuan.setText(jTable1.getValueAt(baris, 4) != null ? jTable1.getValueAt(baris, 4).toString() : "");
        TxtPengirim.setText(jTable1.getValueAt(baris, 5) != null ? jTable1.getValueAt(baris, 5).toString() : "");
        TxtFile.setText(jTable1.getValueAt(baris, 6) != null ? jTable1.getValueAt(baris, 6).toString() : "");
    }

    private void TxtCariKeyReleased(java.awt.event.KeyEvent evt) {
        try {
            String c = TxtCari.getText();
            String cari = "SELECT * FROM surat_keluar WHERE idk LIKE '%" + c + "%' OR no_suratk LIKE '%" + c + "%' OR perihal LIKE '%" + c + "%'";
            crudObj.loadData(jTable1, cari);
        } catch (Exception e) {
            System.out.print(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtPerihal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtTujuan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtPengirim = new javax.swing.JTextField();
        TxtNoSurat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtFile = new javax.swing.JTextField();
        TxtTanggal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        TxtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Perihal");

        TxtTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTujuanActionPerformed(evt);
            }
        });

        jLabel6.setText("Tujuan");

        TxtPengirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPengirimActionPerformed(evt);
            }
        });

        TxtNoSurat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNoSuratActionPerformed(evt);
            }
        });

        jLabel7.setText("Pengirim");

        jLabel2.setText("No Surat");

        TxtFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFileActionPerformed(evt);
            }
        });

        TxtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTanggalActionPerformed(evt);
            }
        });

        jLabel8.setText("File");

        jLabel3.setText("Tanggal (YYYY-MM-DD)");

        jLabel1.setText("ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("FORM SURAT KELUAR");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtFile, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TxtPengirim)
                                    .addComponent(TxtTujuan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtPerihal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtNoSurat)
                                .addComponent(TxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(TxtCari, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNoSurat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(TxtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPerihal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(TxtFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTanggalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String idk = TxtID.getText();
            String no_suratk = TxtNoSurat.getText();
            String tglk = TxtTanggal.getText();
            String perihal = TxtPerihal.getText();
            String tujuan = TxtTujuan.getText();
            String pengirimk = TxtPengirim.getText();
            String filek = TxtFile.getText();

            if (idk.isEmpty() || no_suratk.isEmpty() || tglk.isEmpty()) {
                JOptionPane.showMessageDialog(null, "ID, No Surat, dan Tanggal wajib diisi!");
                return;
            }

            crudObj.simpanSuratKeluarStatement(idk, no_suratk, tglk, perihal, tujuan, pengirimk, filek);

            if (crudObj.validasi) {
                TxtNoSurat.setText(crudObj.var_no_suratk_skel);
                TxtTanggal.setText(crudObj.var_tglk_skel);
                TxtPerihal.setText(crudObj.var_perihal_skel);
                TxtTujuan.setText(crudObj.var_tujuan_skel);
                TxtPengirim.setText(crudObj.var_pengirimk_skel);
                TxtFile.setText(crudObj.var_filek_skel);
            }
            crudObj.loadData(jTable1, "SELECT * FROM surat_keluar");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }


    private void TxtNoSuratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNoSuratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNoSuratActionPerformed

    private void TxtTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTujuanActionPerformed

    private void TxtPengirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPengirimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPengirimActionPerformed

    private void TxtFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFileActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {
        if (
            TxtID.getText().isEmpty() ||
            TxtNoSurat.getText().isEmpty() ||
            TxtTanggal.getText().isEmpty()
           ){
            JOptionPane.showMessageDialog(null, "Pilih data dari tabel terlebih dahulu!");
            return;
        }

        crudObj.ubahSuratKeluarPrepared(
                TxtID.getText(),
                TxtNoSurat.getText(),
                TxtTanggal.getText(),
                TxtPerihal.getText(),
                TxtTujuan.getText(),
                TxtPengirim.getText(),
                TxtFile.getText()
        );
        crudObj.loadData(jTable1, "SELECT * FROM surat_keluar");
    }


    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {
        if (TxtID.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(null, "Pilih data dari tabel untuk dihapus!");
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data ID: " + TxtID.getText() + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            
            crudObj.hapusSuratKeluarPrepared(TxtID.getText());
            clearForm();
            
            crudObj.loadData(jTable1, "SELECT * FROM surat_keluar");
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framesuratkeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framesuratkeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framesuratkeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framesuratkeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framesuratkeluar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtCari;
    private javax.swing.JTextField TxtFile;
    private javax.swing.JTextField TxtID;
    private javax.swing.JTextField TxtNoSurat;
    private javax.swing.JTextField TxtPengirim;
    private javax.swing.JTextField TxtPerihal;
    private javax.swing.JTextField TxtTanggal;
    private javax.swing.JTextField TxtTujuan;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}