/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import pbo_2310010218.CRUD;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.*;
import javax.swing.*;

/**
 *
 * @author LENOVO
 */
public class framelaporankebakaran extends javax.swing.JFrame {

    private CRUD crudObj;

    /**
     * Creates new form framelaporankebakaran
     */
    public framelaporankebakaran() {
        initComponents();
        this.setLocationRelativeTo(null);
        crudObj = new CRUD();
        
        crudObj.loadData(jTable1, "SELECT * FROM laporan_kebakaran");

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });

        TxtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCariKeyReleased(evt);
            }
        });
    }

    private void autoFill(javax.swing.JTextField field, javax.swing.JTable table, int row, int col) {
        field.setText(table.getValueAt(row, col) != null ? table.getValueAt(row, col).toString() : "");
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        int baris = jTable1.getSelectedRow();
        if (baris == -1) {
            return;
        }
        autoFill(TxtID, jTable1, baris, 0);
        autoFill(TxtAlamat, jTable1, baris, 1);
        autoFill(TxtWaktu, jTable1, baris, 2); 
        autoFill(TxtLap, jTable1, baris, 3); 
        autoFill(jTextField5, jTable1, baris, 4); 
        autoFill(TxtLak, jTable1, baris, 5);
        autoFill(TxtJenis, jTable1, baris, 6);
        autoFill(TxtLuas, jTable1, baris, 7);
        autoFill(TxtJuamlah, jTable1, baris, 8); 
        autoFill(TxtTaksiran, jTable1, baris, 9);
        autoFill(TxtJarak, jTable1, baris, 10);
        autoFill(TxtPerjalanan, jTable1, baris, 11);
        autoFill(TxtArmada, jTable1, baris, 12);
        autoFill(TxtKekurangan, jTable1, baris, 13);
        autoFill(TxtPelapor, jTable1, baris, 14);
        autoFill(TxtFile, jTable1, baris, 15);
    }
    
    private void TxtCariKeyReleased(java.awt.event.KeyEvent evt) {
        try {
            String c = TxtCari.getText();
            String cari = "SELECT * FROM laporan_kebakaran WHERE id LIKE '%" + c + "%' OR alamat LIKE '%" + c + "%' OR pelapor LIKE '%" + c + "%'";
            crudObj.loadData(jTable1, cari);
        } catch (Exception e) {
            System.out.print(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtID = new javax.swing.JTextField();
        TxtAlamat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtWaktu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtLap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtLak = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtJenis = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtLuas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtJuamlah = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtTaksiran = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TxtJarak = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtPerjalanan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TxtArmada = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxtKekurangan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtPelapor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TxtFile = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        TxtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("Alamat");

        TxtWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtWaktuActionPerformed(evt);
            }
        });

        jLabel3.setText("Tanggal");

        jLabel4.setText("Waktu");

        jLabel5.setText("Lap");

        jLabel6.setText("Lak");

        jLabel7.setText("Jenis");

        jLabel8.setText("Luas");

        TxtJuamlah.setText(" ");
        TxtJuamlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtJuamlahActionPerformed(evt);
            }
        });

        jLabel9.setText("Jumlah");

        jLabel10.setText("Taksiran");

        jLabel11.setText("Jarak");

        jLabel12.setText("Perjalanan");

        jLabel13.setText("Armada");

        jLabel14.setText("Kekurangan");

        TxtPelapor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPelaporActionPerformed(evt);
            }
        });

        jLabel15.setText("Pelapor");

        jLabel16.setText("File");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel17.setText("LAPORAN KEBAKARAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtID)
                                .addGap(503, 503, 503))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(btnSimpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUbah)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnHapus))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(357, 357, 357)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(TxtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel10))
                                                .addGap(91, 91, 91)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TxtTaksiran)
                                                    .addComponent(TxtJarak)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel14))
                                                .addGap(72, 72, 72)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TxtKekurangan, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(TxtArmada)
                                                    .addComponent(TxtPerjalanan)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel16))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(97, 97, 97)
                                                        .addComponent(TxtFile))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(94, 94, 94)
                                                        .addComponent(TxtPelapor)))))))
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(TxtJuamlah, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtLuas, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TxtJenis, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                .addComponent(TxtLak, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtWaktu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtLap, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(421, 421, 421))))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel17)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel17)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(TxtWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TxtLak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TxtJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(TxtLuas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TxtJuamlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TxtTaksiran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TxtJarak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(TxtPerjalanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TxtArmada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(TxtKekurangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(TxtPelapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(TxtFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String id = TxtID.getText();
            if (id.isEmpty()) {
                JOptionPane.showMessageDialog(null, "ID wajib diisi!");
                return;
            }
            
            String alamat = TxtAlamat.getText();
            String tgl = TxtWaktu.getText(); 
            String waktu = TxtLap.getText(); 
            String lap = jTextField5.getText(); 
            String lak = TxtLak.getText();
            String jenis = TxtJenis.getText();
            String luas = TxtLuas.getText();
            String jumlah = TxtJuamlah.getText().trim(); 
            String taksiran = TxtTaksiran.getText();
            String jarak = TxtJarak.getText();
            String perjalanan = TxtPerjalanan.getText();
            String armada = TxtArmada.getText();
            String kekuatan = TxtKekurangan.getText(); 
            String pelapor = TxtPelapor.getText();
            String file = TxtFile.getText();

            crudObj.simpanLaporanStatement(id, alamat, tgl, waktu, lap, lak, jenis, luas, jumlah, taksiran, jarak, perjalanan, armada, kekuatan, pelapor, file);

            if (crudObj.validasi) {
                TxtAlamat.setText(crudObj.var_alamat_lap);
                TxtWaktu.setText(crudObj.var_tgl_lap);
                TxtLap.setText(crudObj.var_waktu_lap);
                jTextField5.setText(crudObj.var_lap_lap);
                TxtLak.setText(crudObj.var_lak_lap);
                TxtJenis.setText(crudObj.var_jenis_lap);
                TxtLuas.setText(crudObj.var_luas_lap);
                TxtJuamlah.setText(crudObj.var_jumlah_lap);
                TxtTaksiran.setText(crudObj.var_taksiran_lap);
                TxtJarak.setText(crudObj.var_jarak_lap);
                TxtPerjalanan.setText(crudObj.var_perjalanan_lap);
                TxtArmada.setText(crudObj.var_armada_lap);
                TxtKekurangan.setText(crudObj.var_kekuatan_lap);
                TxtPelapor.setText(crudObj.var_pelapor_lap);
                TxtFile.setText(crudObj.var_file_lap);
            }
            crudObj.loadData(jTable1, "select * from laporan_kebakaran");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    private void TxtWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtWaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtWaktuActionPerformed

    private void TxtJuamlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtJuamlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtJuamlahActionPerformed

    private void TxtPelaporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPelaporActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPelaporActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {
        if (TxtID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Silakan pilih data terlebih dahulu");
            jTable1.requestFocus();
        } else {
            crudObj.ubahLaporanPrepared(
                    TxtID.getText(),
                    TxtAlamat.getText(),
                    TxtWaktu.getText(),
                    TxtLap.getText(),
                    jTextField5.getText(),
                    TxtLak.getText(),
                    TxtJenis.getText(),
                    TxtLuas.getText(),
                    TxtJuamlah.getText().trim(),
                    TxtTaksiran.getText(),
                    TxtJarak.getText(),
                    TxtPerjalanan.getText(),
                    TxtArmada.getText(),
                    TxtKekurangan.getText(),
                    TxtPelapor.getText(),
                    TxtFile.getText()
            );
            crudObj.loadData(jTable1, "SELECT * FROM laporan_kebakaran");
        }
    }

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {
        if (TxtID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Silakan pilih data terlebih dahulu");
            jTable1.requestFocus();
        } else {
            int konfirmasi = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data ID: " + TxtID.getText() + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            if (konfirmasi == JOptionPane.YES_OPTION) {
                
                crudObj.hapusLaporanPrepared(TxtID.getText());
                
                TxtID.setText(null);
                TxtAlamat.setText(null);
                TxtWaktu.setText(null); 
                TxtLap.setText(null); 
                jTextField5.setText(null); 
                TxtLak.setText(null);
                TxtJenis.setText(null);
                TxtLuas.setText(null);
                TxtJuamlah.setText(null); 
                TxtTaksiran.setText(null);
                TxtJarak.setText(null);
                TxtPerjalanan.setText(null);
                TxtArmada.setText(null);
                TxtKekurangan.setText(null); 
                TxtPelapor.setText(null);
                TxtFile.setText(null);
                
                crudObj.loadData(jTable1, "SELECT * FROM laporan_kebakaran");
            }
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framelaporankebakaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framelaporankebakaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framelaporankebakaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framelaporankebakaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framelaporankebakaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtAlamat;
    private javax.swing.JTextField TxtArmada;
    private javax.swing.JTextField TxtCari;
    private javax.swing.JTextField TxtFile;
    private javax.swing.JTextField TxtID;
    private javax.swing.JTextField TxtJarak;
    private javax.swing.JTextField TxtJenis;
    private javax.swing.JTextField TxtJuamlah;
    private javax.swing.JTextField TxtKekurangan;
    private javax.swing.JTextField TxtLak;
    private javax.swing.JTextField TxtLap;
    private javax.swing.JTextField TxtLuas;
    private javax.swing.JTextField TxtPelapor;
    private javax.swing.JTextField TxtPerjalanan;
    private javax.swing.JTextField TxtTaksiran;
    private javax.swing.JTextField TxtWaktu;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}